"""add bed info

Revision ID: 283c72e96838
Revises: 6e06b2ccfbdb
Create Date: 2018-06-15 09:47:49.521000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283c72e96838'
down_revision = '6e06b2ccfbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_tdtc_fees', sa.Column('end_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_tdtc_fees', 'end_time')
    # ### end Alembic commands ###
