"""initial migration

Revision ID: 322ef4d2c398
Revises: 
Create Date: 2018-06-06 15:35:32.261000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322ef4d2c398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('academy', sa.String(length=64), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('t_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card_no', sa.String(length=20), nullable=True),
    sa.Column('exam_no', sa.String(length=32), nullable=True),
    sa.Column('student_no', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('sex', sa.SMALLINT(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('teacher_name', sa.String(length=24), nullable=True),
    sa.Column('teacher_mobile', sa.String(length=11), nullable=True),
    sa.Column('dorm_no', sa.String(length=32), nullable=True),
    sa.Column('cloth_id', sa.Integer(), nullable=True),
    sa.Column('org_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_student')
    op.drop_table('t_organization')
    # ### end Alembic commands ###
