"""initial migration

Revision ID: 35b89fa314c0
Revises: 283c72e96838
Create Date: 2018-06-21 10:36:58.867000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b89fa314c0'
down_revision = '283c72e96838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_student', sa.Column('bust', sa.String(length=24), nullable=True))
    op.add_column('t_student', sa.Column('height', sa.String(length=24), nullable=True))
    op.add_column('t_student', sa.Column('shoe_size', sa.String(length=24), nullable=True))
    op.add_column('t_student', sa.Column('waist', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_student', 'waist')
    op.drop_column('t_student', 'shoe_size')
    op.drop_column('t_student', 'height')
    op.drop_column('t_student', 'bust')
    # ### end Alembic commands ###
