"""add bed info

Revision ID: 5049e91c8b34
Revises: 322ef4d2c398
Create Date: 2018-06-08 11:46:07.940000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5049e91c8b34'
down_revision = '322ef4d2c398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_bed_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.String(length=32), nullable=True),
    sa.Column('build_name', sa.String(length=32), nullable=True),
    sa.Column('floor_no', sa.String(length=32), nullable=True),
    sa.Column('dorm_no', sa.String(length=32), nullable=True),
    sa.Column('bed_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no')
    )
    op.add_column(u't_student', sa.Column('bed_serial_no', sa.String(length=32), nullable=True))
    op.drop_column(u't_student', 'dorm_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u't_student', sa.Column('dorm_no', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column(u't_student', 'bed_serial_no')
    op.drop_table('t_bed_info')
    # ### end Alembic commands ###
