"""add model

Revision ID: 5bd08103a3de
Revises: 69e65296f116
Create Date: 2018-06-13 10:34:00.726000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd08103a3de'
down_revision = '69e65296f116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_no', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('fee_desc', sa.String(length=128), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=24), nullable=True),
    sa.Column('group', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fee_no')
    )
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('student_no', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('pay_amt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('t_order_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('fee_no', sa.String(length=24), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_student_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=24), nullable=True),
    sa.Column('method', sa.String(length=24), nullable=True),
    sa.Column('req_data', sa.String(length=1024), nullable=True),
    sa.Column('resp_data', sa.String(length=1024), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_student_log')
    op.drop_table('t_order_fees')
    op.drop_table('t_order')
    op.drop_table('t_fees')
    # ### end Alembic commands ###
