"""add relative

Revision ID: 69e65296f116
Revises: ac10680bdd72
Create Date: 2018-06-12 18:59:43.008000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e65296f116'
down_revision = 'ac10680bdd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_relative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('relation_ship', sa.String(length=24), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('address_code', sa.String(length=24), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_relative')
    # ### end Alembic commands ###
