"""add relative

Revision ID: 73ef6a7390c8
Revises: e8ba162eef8a
Create Date: 2018-06-14 11:37:13.049000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ef6a7390c8'
down_revision = 'e8ba162eef8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_tdtc_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('fee_name', sa.String(length=32), nullable=True),
    sa.Column('student_no', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('real_pay_amt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('should_pay_amt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('pay_time', sa.DATETIME(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_tdtc_orders')
    # ### end Alembic commands ###
