"""modfiy student

Revision ID: 85ff5b1aaac5
Revises: 5049e91c8b34
Create Date: 2018-06-11 16:37:46.734000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ff5b1aaac5'
down_revision = '5049e91c8b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_student', sa.Column('is_loan', sa.Integer(), nullable=True))
    op.add_column('t_student', sa.Column('loan_amt', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_student', 'loan_amt')
    op.drop_column('t_student', 'is_loan')
    # ### end Alembic commands ###
