"""add room rule

Revision ID: ac10680bdd72
Revises: 85ff5b1aaac5
Create Date: 2018-06-12 17:19:47.335000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac10680bdd72'
down_revision = '85ff5b1aaac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_room_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_no', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.SMALLINT(), nullable=True),
    sa.Column('bed_no', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.Column('update_time', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u't_student', sa.Column('bed_no', sa.String(length=32), nullable=True))
    op.drop_column(u't_student', 'bed_serial_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u't_student', sa.Column('bed_serial_no', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column(u't_student', 'bed_no')
    op.drop_table('t_room_rule')
    # ### end Alembic commands ###
