"""add model

Revision ID: e8ba162eef8a
Revises: 70c83b17cc78
Create Date: 2018-06-13 16:32:37.249000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ba162eef8a'
down_revision = '70c83b17cc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_room_rule', sa.Column('dorm_no', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_room_rule', 'dorm_no')
    # ### end Alembic commands ###
